//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mech_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int id { get; set; }
        public int customerId { get; set; }
        public string street { get; set; }
        public string street2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public Nullable<System.DateTime> dateRemoved { get; set; }
        public System.DateTime dateAdded { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
