//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mech_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public System.DateTime serviceDate { get; set; }
        public Nullable<int> milage { get; set; }
        public string cause { get; set; }
        public string correction { get; set; }
        public string condition { get; set; }
        public int vehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
