//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mech_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Histories = new HashSet<History>();
            this.Customer_Vehicle = new HashSet<Customer_Vehicle>();
        }
    
        public int id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string vinNumber { get; set; }
        public string year { get; set; }
        public string color { get; set; }
        public string engine { get; set; }
        public Nullable<System.DateTime> dateRemoved { get; set; }
        public System.DateTime dateAdded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Vehicle> Customer_Vehicle { get; set; }
    }
}
